server_port: 5000
data_source: "file"
celestrak_configuration:
  all_satellites_url: "https://celestrak.com/NORAD/elements/gp.php?GROUP=active&FORMAT=json"
  geo_satellites_url: "https://celestrak.com/NORAD/elements/gp.php?GROUP=geo&FORMAT=json"
  celestrak_refresh_rate_hours: 12
file_source_configuration:
  source_file_path: "./active_satellites_tle.txt"
  refresh_rate_seconds: 30
