services:
  kratos-tle-provider:
    container_name: tle-provider
    image: funkit/tle-provider
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: ./configuration.yml
        target: /home/appuser/configuration.yml
