name: Build the TLE provider

on:
  push:
    branches: [ main ]
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - name: Build
      run: go build -o tle-provider.exe -v ./...
    - name: Test
      run: go test -v ./...
    - name: Release with Notes
      uses: softprops/action-gh-release@v1
      with:
        files: tle-provider.exe
      env:
        GITHUB_TOKEN: ${{ secrets.REPOSITORY_RELEASE_TOKEN }}
