name: Build the TLE provider

on:
  push:
    
jobs:
  build:
    env:
      artifact_name: ./tle-provider_${{github.ref_name}}.exe
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Build
        run: go build -o $artifact_name
      - name: Test
        run: go test -v ./...
      - name: list files
        run: ls
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ artifact_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.REPOSITORY_RELEASE_TOKEN }}
